services:
#    nfq_weather.example:
#        class: nfq\WeatherBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

  nfq.weather.openweathermap:
    class: nfq\WeatherBundle\Service\OpenMapWeatherServiceProvider
    arguments: ["%nfq.weather.omw.api_key%"]
  nfq.weather.yahoo:
    class: WeatherBundle\Providers\YahooProvider
    arguments: ["%nfq.weather.yh.api_key%"]
